backend/backend/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from school import urls as school_urls
from school import api_urls as school_api_urls
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include(school_urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(school_api_urls)),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

backend/school/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic.base import TemplateView

app_name = "school"

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="school/list.html"),
        name="averages_view"),
    url(r'^students$', TemplateView.as_view(template_name="school/students.html"),
        name="students_view"),
    url(r'^classes$', TemplateView.as_view(template_name="school/classes.html"),
        name="classes_view"),
    url(r'^tests$', TemplateView.as_view(template_name="school/tests.html"),
        name="tests_view"),
    url(r'^grades$', TemplateView.as_view(template_name="school/grades.html"),
        name="grades_view")
]

backend/school/models/final_grade.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .student import Student


class FinalGrade(models.Model):
    """
    Modelo de datos para guardar los promedios de notas finales
    para cada alumno. Se crea para no tener que recalcular el
    promedio cada vez que se revisan las notas, sino que solo
    se recalcule cuando haya un cambio en el promedio de un curso.

    Este modelo se crea considerando que, en el caso de uso dado,
    existen muchas más lecturas que escrituras (cada nota debería
    escribirse una vez solamente, no existen varias pruebas del mismo
    curso en el mismo día, etc.) debido a que los alumnos si pueden
    revisar las notas varias veces.

    Se asume que las notas siempre se aproxima, funcionando en
    un rango de 0 a 100, y que los promedios finales son anuales.

    :Authors:
        - Gabriel Ruiz

    :Last Modification:
        - 2017.08.14
    """
    student = models.ForeignKey(Student, related_name='final_grades',
                                on_delete=models.CASCADE)
    value = models.PositiveSmallIntegerField(_('Value'),
                                             null=True, blank=True)
    classes_qty = models.PositiveSmallIntegerField(_('ClassesQty'),
                                                   null=True, blank=True,
                                                   default=1)
    failing_qty = models.PositiveSmallIntegerField(_('FailingQty'),
                                                   null=True, blank=True,
                                                   default=0)
    year = models.PositiveSmallIntegerField(_('Value'),
                                            null=True, blank=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True,
                                   editable=False)
    updated = models.DateTimeField(_('Updated'), auto_now=True)

    class Meta:
        app_label = 'school'
        verbose_name = _('StudentFinalGrade')
        verbose_name_plural = _('StudentFinalGrades')
        unique_together = ('student', 'year')
        ordering = ['id']

    def __str__(self):
        return "{} - {}".format(str(self.student) if self.student else '',
                                str(self.year))

backend/school/models/school_class.py
# -*- coding: utf-8 -*-
"""
La clase SchoolClass describe los atributos de un curso.

IMPORTANTE: Sobre la relación M2M de alumnos y cursos, es
posible hacerlo de dos formas:

- Crear una clase en particular (por ejemplo, 'StudentsInClass')
que desacople la relación M2M en dos.
- Ocupar la clase ManyToManyField de Django para describir esta
relación. Se ocupará esta clase en este caso, para aprovechar
mejor las características que ofrece Django.

"""
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from .student import Student


class SchoolClass(models.Model):
    """
    Modelo de datos para un curso. Se le llamó 'SchoolClass' en
    lugar de 'Class' para evitar cualquier conflicto o confusión
    posible con la palabra reservada 'class'.
    En este caso, se asume que un 'curso' se refiere a una clase
    estilo universitario, es decir, de una materia en particular.
    Se piensa así a causa del postulado de que 'cada alumno puede
    estar en más de un curso'.

    Al eliminar la clase el atributo 'Teacher' queda como NULL, para
    que otro profesor pueda tomar el curso.
    Se asume que cada registro de curso corresponde solo a un año, para
    mantener un correcto registro de los alumnos que cada curso ha tenido
    en el tiempo.
    Para hacer tracking de los cambios de profesor, se puede ocupar
    una librería como django-simple-history.

    :Authors:
        - Gabriel Ruiz

    :Last Modification:
        - 2017.08.11
    """
    teacher = models.ForeignKey(User, related_name='school_classes',
                                on_delete=models.SET_NULL, null=True, blank=True)
    subject = models.CharField(_('Subject'), max_length=200, null=False,
                               blank=False)
    code = models.CharField(_('ClassCode'), max_length=20, null=False,
                            blank=False, unique=True)
    year = models.PositiveSmallIntegerField(_('Year'), null=False, blank=False)
    students = models.ManyToManyField(Student, related_name="classes", blank=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True,
                                   editable=False)
    updated = models.DateTimeField(_('Updated'), auto_now=True)

    class Meta:
        app_label = 'school'
        verbose_name = _('SchoolClass')
        verbose_name_plural = _('SchoolClass')
        ordering = ['id']

    def __str__(self):
        return "{} {}".format(self.subject, self.code)

backend/school/models/school_test.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .school_class import SchoolClass


class SchoolTest(models.Model):
    """
    Modelo de datos para una prueba. Se le llamó 'SchoolTest' en
    lugar de 'Test' para evitar cualquier conflicto o confusión
    posible con las clases de Test de Django.

    :Authors:
        - Gabriel Ruiz

    :Last Modification:
        - 2017.08.10
    """
    school_class = models.ForeignKey(SchoolClass, related_name="tests")
    datetime = models.DateTimeField(_('DateTime'), null=False, blank=False)
    created = models.DateTimeField(_('Created'), auto_now_add=True,
                                   editable=False)
    updated = models.DateTimeField(_('Updated'), auto_now=True)

    class Meta:
        app_label = 'school'
        verbose_name = _('SchoolTest')
        verbose_name_plural = _('SchoolTests')
        ordering = ['id']

    def __str__(self):
        return str(self.school_class)

backend/school/models/student.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Student(models.Model):
    """
    Modelo de datos para un alumno. No se ocupa la clase User como base,
    considerando que los usuarios no tienen permisos para acceder al
    sistema y con considerados solo como 'registros'.
    Para efectos prácticos, no se consideran datos como RUT, fecha de
    matrícula y otros, que no son necesarios en este caso.

    :Authors:
        - Gabriel Ruiz

    :Last Modification:
        - 2017.08.10
    """
    GENDER = (
        ('f', _('Female')),
        ('m', _('Male'))
    )
    name = models.CharField(_('Name'), max_length=100, null=False, blank=False)
    lastname_1 = models.CharField(_('Lastname1'), max_length=100, null=False, blank=False)
    lastname_2 = models.CharField(_('Lastname2'), max_length=100, null=False, blank=False)
    gender = models.CharField(_('Gender'), choices=GENDER, max_length=1)
    birthday = models.DateField(_('Birthday'), null=True, blank=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True,
                                   editable=False)
    updated = models.DateTimeField(_('Updated'), auto_now=True)


    class Meta:
        app_label = 'school'
        verbose_name = _('Student')
        verbose_name_plural = _('Students')
        ordering = ['id']

    def __str__(self):
        return "{} {} {}".format(self.name, self.lastname_1, self.lastname_2)

backend/school/models/student_class_grade.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .student import Student
from .school_class import SchoolClass


class StudentClassGrade(models.Model):
    """
    Modelo de datos para guardar los promedios de notas de
    cada alumno en cada asignatura. Se crea para no tener
    que recalcular el promedio cada vez que se revisan las
    notas, sino que solo se recalcule cuando haya un cambio
    en las notas de la asignatura en particular.

    Se asume que las notas siempre se aproxima, funcionando en
    un rango de 0 a 100.

    :Authors:
        - Gabriel Ruiz

    :Last Modification:
        - 2017.08.10
    """
    student = models.ForeignKey(Student, related_name='class_grades')
    school_class = models.ForeignKey(SchoolClass, related_name="student_class_grades")
    value = models.PositiveSmallIntegerField(_('Value'), null=True, blank=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True,
                                   editable=False)
    updated = models.DateTimeField(_('Updated'), auto_now=True)

    class Meta:
        app_label = 'school'
        verbose_name = _('StudentClassGrade')
        verbose_name_plural = _('StudentClassGrade')
        ordering = ['id']

    def __str__(self):
        return "{} - {}".format(str(self.student),
                                str(self.school_class))

backend/school/models/student_grade.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .school_test import SchoolTest
from .student import Student


class StudentGrade(models.Model):
    """
    Modelo de datos para guardar las notas de las pruebas tomadas a
    los alummnos.

    :Authors:
        - Gabriel Ruiz

    :Last Modification:
        - 2017.08.10
    """
    student = models.ForeignKey(Student, related_name='grades')
    test = models.ForeignKey(SchoolTest, related_name='student_grades')
    value = models.PositiveSmallIntegerField(_('Value'), null=True, blank=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True,
                                   editable=False)
    updated = models.DateTimeField(_('Updated'), auto_now=True)

    class Meta:
        app_label = 'school'
        verbose_name = _('StudentGrade')
        verbose_name_plural = _('StudentGrades')
        ordering = ['id']

    def __str__(self):
        return "{} - {}".format(str(self.student),
                                str(self.test))

backend/templates/school/classes.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Cursos{% endblock %}

{% block libraries %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="{% static 'js/forms.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          Nuevo curso
        </div>
        <div class="panel-body">
          <form method="post" class="form form-default addition-form" action="{% url 'classes-list' %}" data-classname="classes">
          {% csrf_token %}
          <input type="hidden" name="id" id="id_id">
          <div class="form-group">
            <label class="sr-only" for="id_subject">Asignatura</label>
            <input type="text" name="subject" autofocus="" maxlength="254" class="form-control" placeholder="Asignatura" title="" required="" id="id_subject">
          </div>

          <div class="form-group">
            <label class="sr-only" for="id_teacher_id">Profesor</label>
            <select type="text" name="teacher_id" autofocus="" class="form-control autoload" placeholder="Profesor" title="" required="" id="id_teacher_id" data-type="users">
            </select>
          </div>

          <div class="form-group">
            <label class="sr-only" for="id_code">Código</label>
            <input type="text" name="code" autofocus="" maxlength="10" class="form-control" placeholder="Código" title="" required="" id="id_code">
          </div>

          <div class="form-group">
            <label class="sr-only" for="id_year">Año</label>
            <input type="text" name="year" autofocus="" maxlength="254" class="form-control" placeholder="Año" title="" required="" id="id_year">
          </div>

          <button class="btn btn-default" type="reset">Limpiar</button>
          <button class="btn btn-primary" type="submit">Guardar</button>
        </form>
        </div>
      </div>
    </div>

    <div class="col-sm-8">
      <!-- RESULTADOS -->
       <div id="tableContainer" data-classname="classes">
        <table class="table table-hover">
          <thead>
            <th>ID</th>
            <th>Codigo</th>
            <th>Asignatura</th>
            <th>Profesor</th>
            <th></th>
            <th></th>
          </thead>
          <tbody id="classesContainer">

          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/school/grades.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Notas{% endblock %}

{% block libraries %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="{% static 'js/forms.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          Ingreso de notas
        </div>
        <div class="panel-body">
          <form method="post" class="form form-default addition-form" action="{% url 'grades-list' %}" data-classname="grades">
          {% csrf_token %}
          <input type="hidden" name="id" id="id_id">
          <div class="form-group">
            <label class="sr-only" for="id_test_id">Prueba</label>
            <select type="text" name="test_id" autofocus="" class="form-control autoload" placeholder="Prueba" title="" required="" id="id_test_id" data-type="tests">
            </select>
          </div>

          <div class="form-group">
            <label class="sr-only" for="id_student_id">Alumno</label>
            <select type="text" name="student_id" autofocus="" class="form-control autoload" placeholder="Alumno" title="" required="" id="id_student_id" data-type="students">
            </select>
          </div>

          <div class="form-group">
            <label class="sr-only" for="id_value">Nota</label>
            <input type="text" name="value" autofocus="" maxlength="10" class="form-control" placeholder="Nota" title="" required="" id="id_value">
          </div>

          <button class="btn btn-default" type="reset">Limpiar</button>
          <button class="btn btn-primary" type="submit">Guardar</button>
        </form>
        </div>
      </div>
    </div>

    <div class="col-sm-8">
      <!-- RESULTADOS -->
      <div id="tableContainer" data-classname="grades">
        <table class="table table-hover">
          <thead>
            <th>Prueba</th>
            <th>Alumno</th>
            <th>Nota</th>
            <th></th>
            <th></th>
          </thead>
          <tbody id="gradesContainer">

          </tbody>
        </table>
      </div>

    </div>
  </div>

{% endblock %}

backend/templates/school/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Promedios anuales{% endblock %}

{% block libraries %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          Filtros
        </div>
        <div class="panel-body">
          <a class="btn failing-filter" data-failing="0">Alumnos sin promedios rojos</a>
          <a class="btn failing-filter" data-failing="1">Alumnos con 1 promedio rojo</a>
          <a class="btn failing-filter" data-failing="2">Alumnos con más de 1 promedio rojo</a>
        </div>
      </div>
    </div>

    <div class="col-sm-8">
      <!-- RESULTADOS -->
      <div id="gradesContainer">
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/school/students.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Alumnos{% endblock %}

{% block libraries %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="{% static 'js/forms.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          Nuevo alumno
        </div>
        <div class="panel-body">
          <form method="post" class="form form-default addition-form" action="{% url 'students-list' %}" data-classname="students">
          {% csrf_token %}
          <input type="hidden" name="id" id="id_id">
          <div class="form-group">
            <label class="sr-only" for="id_name">Nombre</label>
            <input type="text" name="name" autofocus="" maxlength="254" class="form-control" placeholder="Nombre" title="" required="" id="id_name">
          </div>

          <div class="form-group">
            <label class="sr-only" for="id_lastname_1">Primer  Apellido</label>
            <input type="text" name="lastname_1" autofocus="" maxlength="254" class="form-control" placeholder="Primer Apellido" title="" required="" id="id_lastname_1">
          </div>

          <div class="form-group">
            <label class="sr-only" for="id_lastname_2">Segundo  Apellido</label>
            <input type="text" name="lastname_2" autofocus="" maxlength="254" class="form-control" placeholder="Segundo Apellido" title="" required="" id="id_lastname_2">
          </div>

          <div class="form-group">
            <label class="sr-only" for="id_gender">Género</label>
            <select type="text" name="gender" autofocus="" class="form-control" placeholder="Género" title="" required="" id="id_gender">
              <option>Sexo</option>
              <option value="f">Femenino</option>
              <option value="m">Masculino</option>
            </select>
          </div>

          <button class="btn btn-default" type="reset">Limpiar</button>
          <button class="btn btn-primary" type="submit">Guardar</button>
        </form>
        </div>
      </div>
    </div>

    <div class="col-sm-8">
      <!-- RESULTADOS -->
      <div id="tableContainer" data-classname="students">
        <table class="table table-hover">
          <thead>
            <th>ID</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th></th>
            <th></th>
          </thead>
          <tbody id="studentsContainer">

          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/school/tests.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Tests{% endblock %}

{% block libraries %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="{% static 'js/forms.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          Nueva prueba
        </div>
        <div class="panel-body">
          <form method="post" class="form form-default addition-form" action="{% url 'tests-list' %}" data-classname="tests">
          {% csrf_token %}
          <input type="hidden" name="id" id="id_id">
          <div class="form-group">
            <label class="sr-only" for="id_school_class_id">Curso</label>
            <select type="text" name="school_class_id" autofocus="" class="form-control autoload" placeholder="Curso" title="" required="" id="id_school_class_id" data-type="classes">
            </select>
          </div>

          <div class="form-group">
            <label class="sr-only" for="id_datetime">Fecha y Hora</label>
            <input type="text" name="datetime" autofocus="" maxlength="254" class="form-control" placeholder="Fecha y Hora" title="" required="" id="id_datetime">
          </div>

          <button class="btn btn-default" type="reset">Limpiar</button>
          <button class="btn btn-primary" type="submit">Guardar</button>
        </form>
        </div>
      </div>
    </div>

    <div class="col-sm-8">
      <!-- RESULTADOS -->
      <div id="tableContainer" data-classname="tests">
        <table class="table table-hover">
          <thead>
            <th>ID</th>
            <th>Curso</th>
            <th>Fecha/Hora</th>
            <th></th>
            <th></th>
          </thead>
          <tbody id="testsContainer">

          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}