backend/backend/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from school import urls as school_urls
from school import api_urls as school_api_urls
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include(school_urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(school_api_urls)),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

backend/school/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic.base import TemplateView

app_name = "school"

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="school/list.html"),
        name="averages_view"),
    url(r'^students$', TemplateView.as_view(template_name="school/students.html"),
        name="students_view"),
    url(r'^classes$', TemplateView.as_view(template_name="school/classes.html"),
        name="classes_view"),
    url(r'^tests$', TemplateView.as_view(template_name="school/tests.html"),
        name="tests_view"),
    url(r'^grades$', TemplateView.as_view(template_name="school/grades.html"),
        name="grades_view")
]

backend/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/base.js' %}"></script>
    {% block libraries %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'school:averages_view' %}">Colegio A</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'school:averages_view' %}">Promedios</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'school:students_view' %}">Alumnos</a></li>
              <li><a href="{% url 'school:classes_view' %}">Cursos</a></li>
              <li><a href="{% url 'school:tests_view' %}">Pruebas</a></li>
              <li><a href="{% url 'school:grades_view' %}">Notas</a></li>
              <li><a href="{% url 'logout' %}">Salir</a></li>
            {% else %}
              <li><a href="{% url 'login' %}">Ingresar</a></li>
            {% endif %}
          </ul>
        </div>

      </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>